version: 2
jobs:
  build:
    docker:
     - image: circleci/android:api-25-alpha
    steps:
      - checkout
      - run: gem install bundler
      - run: sudo apt-get update
      - run: sudo curl -sL https://deb.nodesource.com/setup_7.x | sudo bash
      - run: sudo apt-get install -y nodejs
      - run: sudo npm install -g appium
      - run: sudo apt install -y maven
      - run: emulator -avd circleci-android23 -no-audio -no-window &
      - run: mvn clean install