version: 2
jobs:
  build:
    docker:
     - image: circleci/android:api-25-alpha
    steps:
      - checkout
      - run: $ANDROID_HOME/tools/bin/sdkmanager --list
      - run: $ANDROID_HOME/tools/bin/avdmanager create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-25;google_apis;x86_64'
      - run: gem install bundler
      - run: sudo apt-get update
      - run: sudo curl -sL https://deb.nodesource.com/setup_7.x | sudo bash
      - run: sudo apt-get install -y nodejs
      - run: sudo npm install -g appium
      - run: sudo apt install -y maven
      - run: emulator -list-avds
      - run: emulator -avd circleci-android23 -no-audio -no-window
      - run: sudo appium -a 127.0.0.1 -p 4723
      - run: mvn clean install